nodeLinker: node-modules

packageExtensions:
  '@unocss/inspector@*':
    dependencies:
      '@unocss/core': '*'
  unplugin-vue-router@*:
    dependencies:
      '@vue/compiler-sfc': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.0.0.cjs
