nodeLinker: node-modules

packageExtensions:
  "@unocss/inspector@*":
    dependencies:
      "@unocss/core": "*"
  unplugin-vue-router@*:
    dependencies:
      "@vue/compiler-sfc": "*"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
