# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn

      # Runs unit tests
      - name: Run Vitest Unit Tests
        run: yarn test:unit:ci

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          component: true

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
